
on: pull_request
name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    # Change below line to: `runs-on: self-hosted` if running on private repo under rtCamp org.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@master
      env:
        SKIP_FOLDERS: "tests,.github"
        GH_BOT_TOKEN: ${{ secrets.RTBOT_TOKEN }}
      with:
        args: WordPress,WordPress-Core,WordPress-Docs
    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master